//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.Unity.Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.Unity.Configuration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An abstract ContainerConfiguringElement cannot be created. Please specify a concrete type..
        /// </summary>
        internal static string CannotCreateContainerConfiguringElement {
            get {
                return ResourceManager.GetString("CannotCreateContainerConfiguringElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An abstract ExtensionConfigurationElement object cannot be created. Please specify a concrete type..
        /// </summary>
        internal static string CannotCreateExtensionConfigurationElement {
            get {
                return ResourceManager.GetString("CannotCreateExtensionConfigurationElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An abstract InjectionMemberElement object cannot be created. Please specify a concrete type..
        /// </summary>
        internal static string CannotCreateInjectionMemberElement {
            get {
                return ResourceManager.GetString("CannotCreateInjectionMemberElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An abstract ParameterValueElement object cannot be created. Please specify a concrete type..
        /// </summary>
        internal static string CannotCreateParameterValueElement {
            get {
                return ResourceManager.GetString("CannotCreateParameterValueElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string DestinationNameFormat {
            get {
                return ResourceManager.GetString("DestinationNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load section extension type {0}..
        /// </summary>
        internal static string ExtensionTypeNotFound {
            get {
                return ResourceManager.GetString("ExtensionTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension type {0} does not derive from SectionExtension..
        /// </summary>
        internal static string ExtensionTypeNotValid {
            get {
                return ResourceManager.GetString("ExtensionTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension element type {0} that is being added does not derive from ContainerConfiguringElement, InjectionMemberElement, or ParameterValueElement. An extension element must derive from one of these types..
        /// </summary>
        internal static string InvalidExtensionElementType {
            get {
                return ResourceManager.GetString("InvalidExtensionElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid attributes were found to construct the value for the {0}. Please check the configuration file..
        /// </summary>
        internal static string InvalidValueAttributes {
            get {
                return ResourceManager.GetString("InvalidValueAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration is incorrect, the type {0} does not have a constructor that takes parameters named {1}..
        /// </summary>
        internal static string NoMatchingConstructor {
            get {
                return ResourceManager.GetString("NoMatchingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration is incorrect, the type {0} does not have a method named {1} that takes parameters named {2}..
        /// </summary>
        internal static string NoMatchingMethod {
            get {
                return ResourceManager.GetString("NoMatchingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not have a property named {1}..
        /// </summary>
        internal static string NoSuchProperty {
            get {
                return ResourceManager.GetString("NoSuchProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration is set to inject an array, but the type {0} is not an array type..
        /// </summary>
        internal static string NotAnArray {
            get {
                return ResourceManager.GetString("NotAnArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute {0} must be present and non-empty..
        /// </summary>
        internal static string RequiredPropertyMissing {
            get {
                return ResourceManager.GetString("RequiredPropertyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} is a generic parameter. You cannot specify a specific value for generic parameters..
        /// </summary>
        internal static string ValueNotAllowedForGenericParameter {
            get {
                return ResourceManager.GetString("ValueNotAllowedForGenericParameter", resourceCulture);
            }
        }
    }
}
