using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.Practices.Unity.Configuration;
using Microsoft.Practices.Unity.InterceptionExtension.Configuration.Properties;

namespace Microsoft.Practices.Unity.InterceptionExtension.Configuration
{
    /// <summary>
    /// Configuration element that lets you specify additional interfaces
    /// to add when this type is intercepted.
    /// </summary>
    public class AddInterfaceElement : InjectionMemberElement
    {
        private const string TypeNamePropertyName = "type";

        /// <summary>
        /// Type of interface to add.
        /// </summary>
        [ConfigurationProperty(TypeNamePropertyName, IsRequired = true)]
        public string TypeName
        {
            get { return (string) base[TypeNamePropertyName]; }
            set { base[TypeNamePropertyName] = value; }
        }

        /// <summary>
        /// Each element must have a unique key, which is generated by the subclasses.
        /// </summary>
        public override string Key
        {
            get { return "addInterface: " + TypeName; }
        }

        /// <summary>
        /// Return the set of <see cref="InjectionMember"/>s that are needed
        /// to configure the container according to this configuration element.
        /// </summary>
        /// <param name="container">Container that is being configured.</param>
        /// <param name="fromType">Type that is being registered.</param>
        /// <param name="toType">Type that <paramref name="fromType"/> is being mapped to.</param>
        /// <param name="name">Name this registration is under.</param>
        /// <returns>One or more <see cref="InjectionMember"/> objects that should be
        /// applied to the container registration.</returns>
        public override IEnumerable<InjectionMember> GetInjectionMembers(IUnityContainer container, Type fromType, Type toType, string name)
        {
            Type interfaceType = TypeResolver.ResolveType(TypeName);
            GuardInterfaceTypeFound(interfaceType);
            return new[] {new AdditionalInterface(interfaceType)};
        }

        private void GuardInterfaceTypeFound(Type type)
        {
            if(type == null)
            {
                throw new InvalidOperationException(
                    string.Format(CultureInfo.CurrentUICulture,
                        Resources.CouldNotResolveType, TypeName));
            }
        }
    }
}
