//===============================================================================
// Microsoft patterns & practices
// Unity Application Block
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.Unity.InterceptionExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.Unity.InterceptionExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercepted abstract method was invoked..
        /// </summary>
        internal static string ExceptionAbstractMethodNotImplemented {
            get {
                return ResourceManager.GetString("ExceptionAbstractMethodNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional interfaces do not have an implementation..
        /// </summary>
        internal static string ExceptionAdditionalInterfaceNotImplemented {
            get {
                return ResourceManager.GetString("ExceptionAdditionalInterfaceNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The additional interfaces supplied are invalid: {0}.
        /// </summary>
        internal static string ExceptionAdditionalInterfacesInvalid {
            get {
                return ResourceManager.GetString("ExceptionAdditionalInterfacesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must be a subclass of System.Attribute..
        /// </summary>
        internal static string ExceptionAttributeNoSubclassOfAttribute {
            get {
                return ResourceManager.GetString("ExceptionAttributeNoSubclassOfAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create instance of type {0} with no constructor arguments..
        /// </summary>
        internal static string ExceptionCannotCreateInstance {
            get {
                return ResourceManager.GetString("ExceptionCannotCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection contains a null element..
        /// </summary>
        internal static string ExceptionContainsNullElement {
            get {
                return ResourceManager.GetString("ExceptionContainsNullElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of interfaces is null..
        /// </summary>
        internal static string ExceptionNullInterfacesCollection {
            get {
                return ResourceManager.GetString("ExceptionNullInterfacesCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required interfaces for behavior {1} are invalid: {0}.
        /// </summary>
        internal static string ExceptionRequiredInterfacesInvalid {
            get {
                return ResourceManager.GetString("ExceptionRequiredInterfacesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not an interface..
        /// </summary>
        internal static string ExceptionTypeIsNotInterface {
            get {
                return ResourceManager.GetString("ExceptionTypeIsNotInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null type..
        /// </summary>
        internal static string ExceptionTypeIsNull {
            get {
                return ResourceManager.GetString("ExceptionTypeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is an open generic..
        /// </summary>
        internal static string ExceptionTypeIsOpenGeneric {
            get {
                return ResourceManager.GetString("ExceptionTypeIsOpenGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not interceptable..
        /// </summary>
        internal static string InterceptionNotSupported {
            get {
                return ResourceManager.GetString("InterceptionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the implementation of interface method {0}.{1} in type {2}.
        /// </summary>
        internal static string InterfaceMethodNotImplemented {
            get {
                return ResourceManager.GetString("InterfaceMethodNotImplemented", resourceCulture);
            }
        }
    }
}
